version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - yvea_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  yvea_data:
