export enum MarketplaceCategory {
  DIGITAL_SOLUTIONS = "DIGITAL_SOLUTIONS",
  EDUCATION_TRAINING = "EDUCATION_TRAINING",
  FINANCE_LEGAL = "FINANCE_LEGAL",
  CERTIFICATIONS_TESTS = "CERTIFICATIONS_TESTS",
  LOGISTICS_TRANSPORTATION = "LOGISTICS_TRANSPORTATION",
  MARKET_EXPANSION = "MARKET_EXPANSION",
  COMPLIANCE_QUALITY = "COMPLIANCE_QUALITY",
}
